spring:
  application:
    name: employee-view-service
    
vaadin:
  launch-browser: true

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health, info

grpc:
  server:
    port: 6581
  client:
    auth-service:
      address: 'static://localhost:6570'
      enableKeepAlive: true
      keepAliveTime: 10s
      keepAliveTimeout: 5s
      keepAliveWithoutCalls: false
      negotiationType: PLAINTEXT
    main-service:
      address: 'static://localhost:6565'
      enableKeepAlive: true
      keepAliveTime: 10s
      keepAliveTimeout: 5s
      keepAliveWithoutCalls: false
      negotiationType: PLAINTEXT
